version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s %(levelname) -10s %(name) -10s %(funcName) -15s %(lineno) 5d: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
  file: &file_args
    # class: logging.handlers.RotatingFileHandler
    class: logging.handlers.WatchedFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    # maxBytes: 4194304 # 1024 * 1024 * 4
    # backupCount: 10
    encoding: utf8
  error:
    <<: *file_args
    level: ERROR
    filename: logs/error.log
loggers:
  uvicorn:
    level: INFO
  urllib3:
    level: INFO
    propagate: True
root:
  level: INFO
  handlers: [error, file]
