# -*- coding: utf-8

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s %(levelname) -10s %(name) -10s %(funcName) -15s %(lineno) 5d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO # ERROR
      formatter: simple
      stream: ext://sys.stdout
    file: &file_args
      class : logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: logs/fast_monitor.log
      maxBytes: 4194304 # 1024 * 1024 * 4
      backupCount: 10
    error:
      <<: *file_args
      level: ERROR
      filename: logs/fast_monitor-error.log
  loggers:
    fast_monitor:
      level: DEBUG
      handlers: [ console, error, file ]
    uvicorn:
      level: DEBUG
  root:
    level: DEBUG
