version: '3'

services:
  fast_monitor:
    container_name: fast_monitor
#    image: 'promsoft/port_manager'
    build: .
#    restart: always
    env_file:
    - .env

    ports:
    - "7777:7777"

networks:
  default:
    external:
      name: promsoft